import UnitTangentIterates.ConfiguredCanonicalPairSource
import UnitTangentIterates.ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray
import UnitTangentIterates.ConfiguredRecursiveEdgePhysicalGeometricBase
import UnitTangentIterates.FiniteSmoothRearFamilyMarkingAwareCorrelatedPresentedInfiniteArray

/-!
# Configured physical sidecars for a presented array

This adapter packages the two facts retained by the concrete depthwise array:
its cells use the configured physical curvature cap, and their phase-corrected
fronts stay in the configured common tube.  All quantitative row bounds and
all mixed finite kinematics are then constructed, rather than supplied as
callbacks.
-/

noncomputable section

open Function Set MarkedSpace PathMetric

namespace ConfiguredRecursiveEdgePresentedPhysicalSidecars

open ConfiguredCanonicalPairSource
  ConfiguredCombinedPhysicalDiagonalLargeSeparation
  ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray
  ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorTower
  FiniteSmoothRearFamilyMarkingAwareCorrelatedPresentedInfiniteArray
  FiniteSmoothRearFamilyMarkingAwareFiniteCorrelatedPresentedColumn
  FiniteSmoothRearFamilyMarkingAwareGeometricPresentedArray
  FiniteSmoothRearFamilyMarkingAwarePresentedExplicitPhysicalArrays

open FiniteSmoothRearFamilyMarkingAwarePresentedExplicitPhysicalArrays.GeometricArray

variable {Q : ℕ → Data} {P : ℕ → ℕ → Data}
  {e : ℕ → ℕ → ℝ}
  {P0 P1 khat G1 Cg C : ℕ → ℝ}

/-- The concrete information retained by cells of the configured direct
array.  This is a proof package, not a geometric or scalar callback: the
direct depth adapter fills both fields from its definitions. -/
structure CellFacts
    (D : ConstructedConfiguredSequenceWeighted.Data)
    (A : Array Q P e P0 P1 khat G1 Cg C (commonC D) (commonDlt D)) where
  baseTube : ∀ n,
    IsTubeMember (commonC D) 0 (commonDlt D) (P n 0)
  cellKh : ∀ n k, (A.cell n k).state.kh = sourceKh
  cellFrontTube : ∀ n k,
    IsTubeMember (commonC D) 0 (commonDlt D)
      (A.cell n k).physicalFront

namespace Depthwise

variable {baseMass : ℕ → ℝ} {kh Qmax : ℕ → ℝ}
  {c dlt : ℝ} {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}

/-- Minimal coherence with the reindexed configured physical base.  It avoids
dependent equality between finite columns whose bookkeeping tube parameters
may differ, while retaining exactly the source and initial data used by the
physical proof. -/
structure ConfiguredBaseCoherence
    (B : DepthwiseDepth D baseMass Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    where
  phase : ℕ → ℝ
  terminal_eq : ∀ n,
    FiniteSmoothRearFamilyMarkingAwarePresentedTerminalGeometry.unitTangentData
        (B.column.source n) =
      MarkedShift.shiftData (phase n) (B.ready.row (n + 1)).p
  ready_speed : ∀ n u v,
    ‖(B.ready.row n).p.2.1 u‖ = ‖(B.ready.row n).p.2.1 v‖

/-- The only front phase fact that is not generated by a successor bundle is
the configured depth-zero edge. -/
structure BaseFrontPhaseLink
    (B : DepthwiseDepth D baseMass Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : DepthwiseProvider D baseMass Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1) where
  phase : ℕ → ℝ
  front_eq : ∀ n,
    (B.ready.row n).terminalInput.frontData =
      MarkedShift.shiftData (phase n)
      (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P B M
          (n + 1) 0)

/-- Convert the configured finite-column terminal phase theorem into the
single depth-zero link used by the dependent tower. -/
def BaseFrontPhaseLink.ofSourceTerminal
    (B : DepthwiseDepth D baseMass Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : DepthwiseProvider D baseMass Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1)
    (phase : ℕ → ℝ)
    (hterminal : ∀ n,
      FiniteSmoothRearFamilyMarkingAwarePresentedTerminalGeometry.unitTangentData
          (B.column.source n) =
        MarkedShift.shiftData (phase n) (B.ready.row (n + 1)).p) :
    BaseFrontPhaseLink B M where
  phase := phase
  front_eq := by
    intro n
    rw [(B.ready.row n).frontData_eq]
    simpa [ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P,
      ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.coherentPhase]
      using hterminal n

/-- The configured base invariant supplies the one depth-zero front link. -/
def ConfiguredBaseCoherence.baseFrontPhaseLink
    (B : DepthwiseDepth D baseMass Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : DepthwiseProvider D baseMass Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1)
    (H : ConfiguredBaseCoherence B) :
    BaseFrontPhaseLink B M :=
  BaseFrontPhaseLink.ofSourceTerminal B M H.phase H.terminal_eq

/-- Constant speed of the direct depth-zero display follows from the
configured shifted physical initial datum. -/
theorem ConfiguredBaseCoherence.base_speed
    (B : DepthwiseDepth D baseMass Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : DepthwiseProvider D baseMass Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1)
    (H : ConfiguredBaseCoherence B) :
    ∀ n u v,
      ‖(ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
        B M n 0).2.1 u‖ =
      ‖(ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
        B M n 0).2.1 v‖ := by
  intro n u v
  simpa [ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P,
    ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.coherentPhase]
    using H.ready_speed n u v

/-- Exact terminal-front phase linkage propagates through the entire
dependent scaled-successor tower. -/
theorem terminalFront_eq_shift_P
    (B : DepthwiseDepth D baseMass Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : DepthwiseProvider D baseMass Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1) (H : BaseFrontPhaseLink B M) :
    ∀ n k, ∃ q,
      ((depthwiseDepths B M k).ready.row n).terminalInput.frontData =
        MarkedShift.shiftData q
          (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
            B M (n + 1) k) := by
  intro n k
  cases k with
  | zero => exact ⟨H.phase n, H.front_eq n⟩
  | succ k =>
      let Z := depthwiseDepths B M k
      let I := M.input k Z
      let S := I.step.phaseBundles.bundle n
      refine ⟨S.terminalPhase -
        ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.coherentPhase
          B M (n + 1) k, ?_⟩
      rw [((depthwiseDepths B M (k + 1)).ready.row n).frontData_eq]
      change FiniteSmoothRearFamilyMarkingAwarePresentedTerminalGeometry.unitTangentData
          S.scaled.source = _
      rw [S.terminal_eq]
      have hselected :
          ((depthwiseDepths B M k).column.source (n + 1)).selectedRearData
              ((depthwiseDepths B M k).ready.row (n + 1)).output.chosen.Delta.T =
            ((depthwiseDepths B M k).ready.row (n + 1)).base := by
        rw [((depthwiseDepths B M k).ready.row
          (n + 1)).output.chosen.time_eq]
        exact PresentedRow.selectedRearData_terminal_eq_base
          ((depthwiseDepths B M k).ready.row (n + 1))
      rw [hselected,
        ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P_succ_eq_shift_base,
        MarkedShift.shiftData_add]
      congr 1
      ring

/-- Every configured cell fact is forced by the direct dependent tower once
the depth-zero physical edge is linked to the next configured initial datum.
There is no positive-depth or per-cell input. -/
def cellFactsOfBasePhase
    (B : DepthwiseDepth D baseMass Q e 0 P0 P1 khat G1 Cg C c dlt
      (fun _ ↦ sourceKh) Qmax)
    (M : DepthwiseProvider D baseMass Q e P0 P1 khat G1 Cg C c dlt
      (fun _ ↦ sourceKh) Qmax
      (fun _ ↦ sourceKh_nonnegative) (fun _ ↦ sourceKh_lt_one))
    {w : ℕ → ℕ → ℝ} {C' : ℕ → ℝ}
    (hw0 : ∀ n k, 0 ≤ w n k) (hws : ∀ n, Summable (w n))
    (htube : ∀ n k, VariableMarkedTube.IsVariableTubeMember
      (commonC D) (C' n) 0
      (commonDlt D)
      (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
        B M n k))
    (hstep : ∀ n k,
      dist
          (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
            B M n k)
          (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
            B M n (k + 1)) ≤
        TriangularMarkedPathSchemeVariableTerminal.rowC
          P0 P1 khat G1 Cg n * w n k)
    (hbaseSpeed : ∀ n u v,
      ‖(ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
        B M n 0).2.1 u‖ =
      ‖(ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
        B M n 0).2.1 v‖)
    (Hphase : BaseFrontPhaseLink B M) :
    CellFacts D
      (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.toArray
        B M hw0 hws htube hstep) where
  baseTube := fun n ↦ ordinaryTubeOfVariableSpeedConst
    (htube n 0) (hbaseSpeed n)
  cellKh := fun _ _ ↦ rfl
  cellFrontTube := by
    intro n k
    let A := ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.toArray
      B M hw0 hws htube hstep
    let hbase : ∀ i, IsTubeMember (commonC D) 0 (commonDlt D)
        (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
          B M i 0) := fun i ↦
      ordinaryTubeOfVariableSpeedConst (htube i 0) (hbaseSpeed i)
    obtain ⟨q, hq⟩ := terminalFront_eq_shift_P B M Hphase n k
    have hp : IsTubeMember (commonC D) 0 (commonDlt D)
        (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
          B M (n + 1) k) := by
      have H := physicalRearTube A
        (fun i ↦ ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
          B M i 0) (fun _ ↦ rfl) hbase (n + 1) k
      simpa [physicalRear_eq_presented A
        (fun i ↦ ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.P
          B M i 0) (fun _ ↦ rfl)] using H
    change IsTubeMember (commonC D) 0 (commonDlt D)
      (ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.physicalFront
        B M n k)
    rw [ConfiguredRecursiveEdgeFiniteCorrelatedDepthwisePresentedArray.physicalFront,
      hq, MarkedShift.shiftData_add]
    exact MarkedShift.isTubeMember_shiftData hp _

end Depthwise

/-- Callback-free construction of the complete configured physical sidecars.
The physical rear is the displayed array itself, beginning with `P n 0`;
the intrinsic bounded acceleration norm and the array's summable marked error
provide all row bounds. -/
def CellFacts.toSidecars
    (D : ConstructedConfiguredSequenceWeighted.Data)
    (A : Array Q P e P0 P1 khat G1 Cg C (commonC D) (commonDlt D))
    (H : CellFacts D A) :
    PresentedPhysical.Sidecars A (fun n ↦ P n 0) sourceKh
      (commonC D) (commonDlt D) (commonC D) (commonDlt D) where
  physical := physicalRowBoundsOfErrorIntrinsic A (fun n ↦ P n 0)
    (fun _ ↦ rfl) H.baseTube D.separation_zero_pos
  mixed := mixedKinematicsOfCells A (fun n ↦ P n 0) H.cellKh
  frontTube := mixedFront_tube_of_cells A (by
      rw [← A.base 0]
      exact H.baseTube 0) H.cellFrontTube

end ConfiguredRecursiveEdgePresentedPhysicalSidecars
