import UnitTangentIterates.ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorMass

/-!
# Configured finite correlated scaled-successor tower

This module iterates the closed composition-scaled successor.  The quantitative
input at each depth is the fully physical recost sidecar; the successor's
analytic source, Ready package, and source-mass invariant are theorem-produced.

The exact spatial coherence is deliberately stated against the constant-speed
presented `base`.  The selected jet endpoint has the same range and is close in
the marked metric, but its general nonaffine marking is not a cyclic shift.
-/

noncomputable section

open Set MeasureTheory MarkedSpace PathMetric

namespace ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorTower

open FiniteSmoothRearFamilyMarkingAwareFiniteCorrelatedPresentedColumn
open ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorMass
open ConfiguredRecursiveEdgeSourceP0Growth

/-- One configured depth, including the quantitative data needed to iterate. -/
structure Depth
    (D : ConstructedConfiguredSequenceWeighted.Data) (stableTarget : ℝ)
    (Q : ℕ → Data) (e : ℕ → ℕ → ℝ) (k : ℕ)
    (P0 P1 khat G1 Cg C : ℕ → ℝ) (c dlt : ℝ)
    (kh Qmax : ℕ → ℝ) where
  current : ℕ → Data
  column : FiniteColumn Q current e k P0 P1 khat G1 Cg C c dlt kh Qmax
  ready : ReadyColumn column
  bounds : RowBounds ready
  sourceMass : SourceMassInvariant column (8 * stableTarget)
    (scaledSuccessorPhysicalDefect D)

/-- The row-local physical input not generated by the scaled successor itself.
It consists of the explicit phase-scaled bundles, their scalar coefficient
estimate, the stable-component recost estimate, and the next row bounds. -/
structure FullyPhysicalRecostInput
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    (Z : Depth D stableTarget Q e k P0 P1 khat G1 Cg C c dlt kh Qmax)
    (hkh0 : ∀ n, 0 ≤ kh n) (hkh1 : ∀ n, kh n < 1)
    (hstable : 0 ≤ stableTarget) where
  bundles : PhaseScaledSuccessorBundles Z.ready Z.bounds
  scaledCoeff_nonnegative : ∀ n, 0 ≤
    (bundles.bundle n).scaled.coeff / Real.sqrt (1 - (kh n) ^ 2)
  scaledCoeff_le : ∀ n,
    (bundles.bundle n).scaled.coeff / Real.sqrt (1 - (kh n) ^ 2) ≤
      2 * edgeCompositionCoeff D n
  recost_cost_le : ∀ n,
    (Z.ready.row (n + 1)).output.chosen.Delta.cost ≤
      4 * stableTarget * edgePhysicalDefect D n
  nextBounds : RowBounds
    ((closedConfiguredRecostedStep bundles D hkh0 hkh1 hstable
      scaledCoeff_nonnegative scaledCoeff_le recost_cost_le).nextReady)

/-- The closed successor determined by a fully physical recost input. -/
noncomputable def FullyPhysicalRecostInput.step
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {Z : Depth D stableTarget Q e k P0 P1 khat G1 Cg C c dlt kh Qmax}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    {hstable : 0 ≤ stableTarget}
    (R : FullyPhysicalRecostInput Z hkh0 hkh1 hstable) :
    ClosedScaledSuccessorStep (target := 8 * stableTarget)
      (defect := scaledSuccessorPhysicalDefect D) Z.ready Z.bounds :=
  closedConfiguredRecostedStep R.bundles D hkh0 hkh1 hstable
    R.scaledCoeff_nonnegative R.scaledCoeff_le R.recost_cost_le

/-- One dependent successor depth. -/
noncomputable def nextDepth
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {Z : Depth D stableTarget Q e k P0 P1 khat G1 Cg C c dlt kh Qmax}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    {hstable : 0 ≤ stableTarget}
    (R : FullyPhysicalRecostInput Z hkh0 hkh1 hstable) :
    Depth D stableTarget Q e (k + 1) P0 P1 khat G1 Cg C c dlt kh Qmax where
  current := Z.ready.nextCurrent
  column := R.step.phaseBundles.toScaled.nextColumn
  ready := R.step.nextReady
  bounds := by simpa [FullyPhysicalRecostInput.step] using R.nextBounds
  sourceMass := R.step.sourceMass

/-- Inputs for every already-constructed depth. -/
structure Provider
    (D : ConstructedConfiguredSequenceWeighted.Data) (stableTarget : ℝ)
    (Q : ℕ → Data) (e : ℕ → ℕ → ℝ)
    (P0 P1 khat G1 Cg C : ℕ → ℝ) (c dlt : ℝ)
    (kh Qmax : ℕ → ℝ)
    (hkh0 : ∀ n, 0 ≤ kh n) (hkh1 : ∀ n, kh n < 1)
    (hstable : 0 ≤ stableTarget) where
  recost : ∀ k
    (Z : Depth D stableTarget Q e k P0 P1 khat G1 Cg C c dlt kh Qmax),
    FullyPhysicalRecostInput Z hkh0 hkh1 hstable

/-- The concrete dependent depth tower. -/
noncomputable def depths
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    {hstable : 0 ≤ stableTarget}
    (B : Depth D stableTarget Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : Provider D stableTarget Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1 hstable) :
    ∀ k, Depth D stableTarget Q e k P0 P1 khat G1 Cg C c dlt kh Qmax
  | 0 => B
  | k + 1 => nextDepth (M.recost k (depths B M k))

@[simp] theorem depths_zero
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    {hstable : 0 ≤ stableTarget}
    (B : Depth D stableTarget Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : Provider D stableTarget Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1 hstable) :
    depths B M 0 = B := rfl

@[simp] theorem depths_succ
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    {hstable : 0 ≤ stableTarget}
    (B : Depth D stableTarget Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : Provider D stableTarget Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1 hstable) (k : ℕ) :
    depths B M (k + 1) =
      nextDepth (M.recost k (depths B M k)) := rfl

/-- Exact sound successor coherence: the new intrinsic initial is a cyclic
shift of the preceding constant-speed presented rear. -/
theorem nextDepth_row_p_eq_shift_base
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {Z : Depth D stableTarget Q e k P0 P1 khat G1 Cg C c dlt kh Qmax}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    {hstable : 0 ≤ stableTarget}
    (R : FullyPhysicalRecostInput Z hkh0 hkh1 hstable) (n : ℕ) :
    ((nextDepth R).ready.row n).p =
      MarkedShift.shiftData (R.step.phaseBundles.bundle n).initialPhase
        (Z.ready.row n).base := by
  rw [ReadyColumn.row_p_eq_initial]
  exact (R.step.phaseBundles.bundle n).initial_eq

/-- The selected nonaffine endpoint and the constant-speed presented rear
have the same unmarked curve image. -/
theorem Depth.endpoint_range_eq_base
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    (Z : Depth D stableTarget Q e k P0 P1 khat G1 Cg C c dlt kh Qmax)
    (hkh0 : ∀ n, 0 ≤ kh n) (hkh1 : ∀ n, kh n < 1) (n : ℕ) :
    range ((Z.ready.row n).output.jets.rear.1) =
      range ((Z.ready.row n).base.1) := by
  let T := (Z.ready.row n).canonicalTarget (hkh0 n) (hkh1 n)
  have h := T.endpoint_range_eq_target
  have hb := T.base_eq
  rw [← hb] at h
  exact h

/-- The endpoint marking defect is kept separate from the exact spatial phase
coherence used by the depth recursion. -/
theorem Depth.endpoint_dist_le_base
    {D : ConstructedConfiguredSequenceWeighted.Data} {stableTarget : ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    (Z : Depth D stableTarget Q e k P0 P1 khat G1 Cg C c dlt kh Qmax)
    (hkh0 : ∀ n, 0 ≤ kh n) (hkh1 : ∀ n, kh n < 1) (n : ℕ) :
    dist (Z.ready.row n).output.jets.rear (Z.ready.row n).base ≤
      FiniteSmoothRearFamilyMarkingAwareChosenCanonicalEndpointCap.exactEndpointCap
        (Z.ready.row n).output := by
  let T := (Z.ready.row n).canonicalTarget (hkh0 n) (hkh1 n)
  have h := T.endpoint_dist_le
  have hb := T.base_eq
  rw [← hb] at h
  exact h

/-! ## Depthwise raw-cost tower

This parallel tower is the recursive source route used after separating
canonical recosting from source construction.  At depth zero it retains the
configured base mass envelope; at every positive depth it carries the exact
row-diagonal mass produced by `RowBounds.cost_le`. -/

/-- Source-mass envelope at one tower depth. -/
def depthwiseMassEnvelope
    (D : ConstructedConfiguredSequenceWeighted.Data)
    (baseMass : ℕ → ℝ) (e : ℕ → ℕ → ℝ) (k n : ℕ) : ℝ :=
  match k with
  | 0 => baseMass n
  | j + 1 => 2 * edgeCompositionCoeff D n * e (n + 1) (j + 1)

/-- The three scalar comparisons needed to widen the theorem-produced
presented increment to the configured row ceilings.  This is strictly less
data than `RowBounds`: its cost estimate is recovered from source mass. -/
structure FlowCeilings
    {Q current : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    (S : FiniteColumn Q current e k P0 P1 khat G1 Cg C c dlt kh Qmax) where
  P1_le : ∀ n,
    GaugeFlowDerivCost.costP1
        (FiniteSmoothRearFamilyMarkingAwareAppliedSource.rearPeriod
          (S.source n) 0)
        (khat n)
        (∫ t in (0 : ℝ)..(S.step.richStage (n + 1)).stage.increment.T,
          (S.source n).m t) ≤ P1 n
  G1_le : ∀ n,
    GaugeFlowDerivCost.costG1
        (FiniteSmoothRearFamilyMarkingAwareAppliedSource.rearPeriod
          (S.source n) 0)
        (khat n) (GaugeMarkedDataOfRearFamily.rearKappa2 (kh n))
        (∫ t in (0 : ℝ)..(S.step.richStage (n + 1)).stage.increment.T,
          (S.source n).m t) ≤ G1 n
  Cg_le : ∀ n,
    (khat n) * GaugeFlowDerivCost.costG1
        (FiniteSmoothRearFamilyMarkingAwareAppliedSource.rearPeriod
          (S.source n) 0)
        (khat n) (GaugeMarkedDataOfRearFamily.rearKappa2 (kh n))
        (∫ t in (0 : ℝ)..(S.step.richStage (n + 1)).stage.increment.T,
          (S.source n).m t) +
      GaugeMarkedDataOfRearFamily.rearKappa2 (kh n) *
        GaugeFlowDerivCost.costP1
          (FiniteSmoothRearFamilyMarkingAwareAppliedSource.rearPeriod
            (S.source n) 0)
          (khat n)
          (∫ t in (0 : ℝ)..(S.step.richStage (n + 1)).stage.increment.T,
            (S.source n).m t) ^ 2 ≤ Cg n

/-- The configured edge ceilings are automatic once the source retains the
configured rear-period cap and has total density mass at most one. -/
def FlowCeilings.ofConfiguredMassOne
    (D : ConstructedConfiguredSequenceWeighted.Data) (MA NA : ℝ)
    {Q current : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 C Qmax : ℕ → ℝ} {c dlt : ℝ}
    (S : FiniteColumn Q current e k P0
      (edgeP1 D MA)
      (fun _ ↦ ConfiguredCombinedPhysicalDiagonalLargeSeparation.analyticKhat D)
      (edgeG1 D MA NA)
      (edgeCgWithKhat D
        (ConfiguredCombinedPhysicalDiagonalLargeSeparation.analyticKhat D) MA NA)
      C c dlt
      (fun _ ↦ ConfiguredCombinedPhysicalDiagonalLargeSeparation.sourceKh) Qmax)
    (hperiod : ∀ n,
      FiniteSmoothRearFamilyMarkingAwareAppliedSource.rearPeriod
        (S.source n) 0 ≤ ConfiguredRecursiveEdgeSourceP0.edgeSpeedCap D n)
    (hmass : ∀ n,
      FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass
        (S.source n) ≤ 1) :
    FlowCeilings S := by
  constructor <;> intro n
  all_goals
    have hM0 : 0 ≤
        FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass
          (S.source n) :=
      FiniteSmoothRearFamilyMarkingAwareChosenVariableJetLinear.sourceMass_nonnegative
        (S.source n)
    have H := flowCeilings_of_mass_one D (MA := MA) (NA := NA) n
      ((S.source n).rear_period_pos 0).le (hperiod n) hM0 (hmass n)
  · simpa [FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass]
      using H.1
  · simpa [FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass,
      ConfiguredCombinedPhysicalDiagonalLargeSeparation.sourceKh_eq]
      using H.2.1
  · simpa [FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass,
      ConfiguredCombinedPhysicalDiagonalLargeSeparation.sourceKh_eq]
      using H.2.2

/-- Once the three configured flow ceilings are known, source mass supplies
the entire quantitative `RowBounds` package. -/
noncomputable def rowBoundsOfFlowCeilings
    {Q current : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {S : FiniteColumn Q current e k P0 P1 khat G1 Cg C c dlt kh Qmax}
    (H : ReadyColumn S) (F : FlowCeilings S)
    (hmass : ∀ n,
      FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass
        (S.source n) ≤ e n (k + 1)) :
    RowBounds H where
  geometry := fun n ↦ by
    let O := (H.row n).output
    apply NormalPathC2IncrementVariableSpeed.IsVariableSpeedNormalPath.mono
      O.chosen.Delta
      (by simpa only [O.stage_eq] using O.stage.increment_geometry)
      ((GaugeMarkedDataOfRearFamily.rearKappa1_nonneg
          (S.source n).kh_nonnegative (S.source n).kh_lt_one).trans
        (S.source n).rearKappa1_le)
      (F.P1_le n) (F.G1_le n) (F.Cg_le n)
  cost_le := fun n ↦ by
    rw [(H.row n).output.chosen.cost_eq]
    simpa [FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass]
      using hmass n

/-- One depth whose recursive source mass is charged to the actual row
diagonal rather than to a fixed stable-component target. -/
structure DepthwiseDepth
    (D : ConstructedConfiguredSequenceWeighted.Data) (baseMass : ℕ → ℝ)
    (Q : ℕ → Data) (e : ℕ → ℕ → ℝ) (k : ℕ)
    (P0 P1 khat G1 Cg C : ℕ → ℝ) (c dlt : ℝ)
    (kh Qmax : ℕ → ℝ) where
  current : ℕ → Data
  column : FiniteColumn Q current e k P0 P1 khat G1 Cg C c dlt kh Qmax
  ready : ReadyColumn column
  bounds : RowBounds ready
  sourceMass : ∀ n,
    FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass
        (column.source n) ≤ depthwiseMassEnvelope D baseMass e k n

/-- The only row-local inputs needed for a depthwise raw successor. -/
structure DepthwiseInput
    {D : ConstructedConfiguredSequenceWeighted.Data} {baseMass : ℕ → ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    (Z : DepthwiseDepth D baseMass Q e k P0 P1 khat G1 Cg C c dlt kh Qmax)
    (hkh0 : ∀ n, 0 ≤ kh n) (hkh1 : ∀ n, kh n < 1) where
  bundles : PhaseScaledSuccessorBundles Z.ready Z.bounds
  scaledCoeff_le : ∀ n,
    (bundles.bundle n).scaled.coeff / Real.sqrt (1 - (kh n) ^ 2) ≤
      2 * edgeCompositionCoeff D n
  nextBounds : RowBounds
    ((ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorMass.PhaseScaledSuccessorBundles.depthwiseClosedStep
      bundles D hkh0 hkh1 scaledCoeff_le).nextReady)

/-- For the forced amplified recurrence, `nextBounds` is not an independent
callback.  The exact raw-mass multiplier is the next diagonal allowance, so
only the three configured flow-ceiling comparisons remain as scalar input. -/
noncomputable def DepthwiseInput.ofAmplified
    {D : ConstructedConfiguredSequenceWeighted.Data} {baseMass : ℕ → ℝ}
    {Q : ℕ → Data} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    (Z : DepthwiseDepth D baseMass Q
      (amplifiedTriangularError D baseMass) k
      P0 P1 khat G1 Cg C c dlt kh Qmax)
    (hkh0 : ∀ n, 0 ≤ kh n) (hkh1 : ∀ n, kh n < 1)
    (bundles : PhaseScaledSuccessorBundles Z.ready Z.bounds)
    (scaledCoeff_le : ∀ n,
      (bundles.bundle n).scaled.coeff / Real.sqrt (1 - (kh n) ^ 2) ≤
        2 * edgeCompositionCoeff D n)
    (ceilings : FlowCeilings bundles.toScaled.nextColumn) :
    DepthwiseInput Z hkh0 hkh1 := by
  let T := ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorMass.PhaseScaledSuccessorBundles.depthwiseClosedStep
    bundles D hkh0 hkh1 scaledCoeff_le
  refine
    { bundles := bundles
      scaledCoeff_le := scaledCoeff_le
      nextBounds := rowBoundsOfFlowCeilings T.nextReady ?_ ?_ }
  · simpa [T,
      ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorMass.PhaseScaledSuccessorBundles.depthwiseClosedStep]
      using ceilings
  · intro n
    calc
      FiniteSmoothRearFamilyMarkingAwareTimeRescaleCostObstruction.sourceMass
          (T.phaseBundles.toScaled.nextColumn.source n) ≤
          2 * edgeCompositionCoeff D n *
            amplifiedTriangularError D baseMass (n + 1) (k + 1) :=
        T.sourceMass.sourceMass_le n
      _ = amplifiedTriangularError D baseMass n ((k + 1) + 1) :=
        rawMassMultiplier_eq_nextAmplifiedError D baseMass n (k + 1)

noncomputable def DepthwiseInput.step
    {D : ConstructedConfiguredSequenceWeighted.Data} {baseMass : ℕ → ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {Z : DepthwiseDepth D baseMass Q e k P0 P1 khat G1 Cg C c dlt kh Qmax}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    (R : DepthwiseInput Z hkh0 hkh1) :
    DepthwiseClosedScaledSuccessorStep Z.ready Z.bounds D :=
  ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorMass.PhaseScaledSuccessorBundles.depthwiseClosedStep
    R.bundles D hkh0 hkh1 R.scaledCoeff_le

/-- The exact positive-depth source mass is generated by the preceding row's
stored cost bound. -/
noncomputable def depthwiseNextDepth
    {D : ConstructedConfiguredSequenceWeighted.Data} {baseMass : ℕ → ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ} {k : ℕ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {Z : DepthwiseDepth D baseMass Q e k P0 P1 khat G1 Cg C c dlt kh Qmax}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    (R : DepthwiseInput Z hkh0 hkh1) :
    DepthwiseDepth D baseMass Q e (k + 1) P0 P1 khat G1 Cg C c dlt kh Qmax where
  current := Z.ready.nextCurrent
  column := R.step.phaseBundles.toScaled.nextColumn
  ready := R.step.nextReady
  bounds := by simpa [DepthwiseInput.step] using R.nextBounds
  sourceMass := by
    intro n
    simpa [depthwiseMassEnvelope] using R.step.sourceMass.sourceMass_le n

/-- Inputs at every already-constructed depth.  Unlike the legacy provider,
this interface has no recost-cost callback. -/
structure DepthwiseProvider
    (D : ConstructedConfiguredSequenceWeighted.Data) (baseMass : ℕ → ℝ)
    (Q : ℕ → Data) (e : ℕ → ℕ → ℝ)
    (P0 P1 khat G1 Cg C : ℕ → ℝ) (c dlt : ℝ)
    (kh Qmax : ℕ → ℝ)
    (hkh0 : ∀ n, 0 ≤ kh n) (hkh1 : ∀ n, kh n < 1) where
  input : ∀ k
    (Z : DepthwiseDepth D baseMass Q e k P0 P1 khat G1 Cg C c dlt kh Qmax),
    DepthwiseInput Z hkh0 hkh1

noncomputable def depthwiseDepths
    {D : ConstructedConfiguredSequenceWeighted.Data} {baseMass : ℕ → ℝ}
    {Q : ℕ → Data} {e : ℕ → ℕ → ℝ}
    {P0 P1 khat G1 Cg C : ℕ → ℝ} {c dlt : ℝ}
    {kh Qmax : ℕ → ℝ}
    {hkh0 : ∀ n, 0 ≤ kh n} {hkh1 : ∀ n, kh n < 1}
    (B : DepthwiseDepth D baseMass Q e 0 P0 P1 khat G1 Cg C c dlt kh Qmax)
    (M : DepthwiseProvider D baseMass Q e P0 P1 khat G1 Cg C c dlt kh Qmax
      hkh0 hkh1) :
    ∀ k, DepthwiseDepth D baseMass Q e k P0 P1 khat G1 Cg C c dlt kh Qmax
  | 0 => B
  | k + 1 => depthwiseNextDepth (hkh0 := hkh0) (hkh1 := hkh1)
      (M.input k (depthwiseDepths B M k))

end ConfiguredRecursiveEdgeFiniteCorrelatedScaledSuccessorTower
