import UnitTangentIterates.QuotientPullbackPaths

/-!
# Coherently presented pullback paths from the phase quotient

`QuotientPullbackPaths` extracts a phase separately at each unshifted edge.
This file accumulates those phases, so the endpoint of one displayed edge is
literally the start of the next.  No path density is recursively reused.
-/

noncomputable section

open MarkedSpace PathMetric PathMetric.NormalPath MarkedShift

namespace QuotientPresentedPullbackPaths

/-- Cumulative phase generated by independently chosen edge phases. -/
def accumulatedPhase (edgePhase : ℕ → ℕ → ℝ) (n : ℕ) : ℕ → ℝ
  | 0 => 0
  | k + 1 => accumulatedPhase edgePhase n k + edgePhase n k

@[simp] theorem accumulatedPhase_zero (edgePhase : ℕ → ℕ → ℝ) (n : ℕ) :
    accumulatedPhase edgePhase n 0 = 0 := rfl

@[simp] theorem accumulatedPhase_succ
    (edgePhase : ℕ → ℕ → ℝ) (n k : ℕ) :
    accumulatedPhase edgePhase n (k + 1) =
      accumulatedPhase edgePhase n k + edgePhase n k := rfl

/-- A triangular array of displayed pullbacks with literal consecutive normal
paths.  The displayed datum is only a phase shift of the genuine selected-
inverse pullback. -/
structure PresentedArray
    (B : Data → Data) (Q : ℕ → Data) (K : ℝ)
    (d : ℕ → ℝ) (eps : ℕ → ℕ → ℝ) where
  edgePhase : ℕ → ℕ → ℝ
  phase : ℕ → ℕ → ℝ
  phase_eq : phase = accumulatedPhase edgePhase
  displayed : ℕ → ℕ → Data
  displayed_eq : ∀ n k, displayed n k =
    shiftData (phase n k) (TubePullbackLimit.pullback B Q n k)
  step : ∀ n k, NormalPath (displayed n k) (displayed n (k + 1))
  step_cost : ∀ n k, cost (step n k) ≤
    QuotientPullbackPaths.pullbackError K d n k + 2 * eps n k

namespace PresentedArray

variable {B : Data → Data} {Q : ℕ → Data} {K : ℝ}
  {d : ℕ → ℝ} {eps : ℕ → ℕ → ℝ}

@[simp] theorem phase_zero (A : PresentedArray B Q K d eps) (n : ℕ) :
    A.phase n 0 = 0 := by rw [A.phase_eq]; rfl

theorem displayed_zero (A : PresentedArray B Q K d eps) (n : ℕ) :
    A.displayed n 0 = Q n := by
  rw [A.displayed_eq, A.phase_zero]
  simp

/-- The actual displayed step costs are summable in every row whenever the
weighted quotient defects and the chosen slack are summable. -/
theorem step_cost_summable
    (A : PresentedArray B Q K d eps) (n : ℕ)
    (hdefect : Summable fun k =>
      QuotientPullbackPaths.pullbackError K d n k)
    (hslack : Summable (eps n)) :
    Summable fun k => cost (A.step n k) := by
  have hmajor : Summable fun k =>
      QuotientPullbackPaths.pullbackError K d n k + 2 * eps n k :=
    hdefect.add (hslack.mul_left 2)
  exact hmajor.of_nonneg_of_le (fun k => (A.step n k).cost_nonneg)
    (A.step_cost n)

end PresentedArray

/-- Build coherent displayed markings from the independently extracted
near-minimizers in `pathDistShift`. -/
theorem exists_presentedArray
    {B : Data → Data} {Q : ℕ → Data} {K : ℝ} {d : ℕ → ℝ}
    (hK : 0 ≤ K)
    (hlip : ∀ p q,
      pathDistShift (B p) (B q) ≤ K * pathDistShift p q)
    (hdefect : ∀ n, pathDistShift (Q n) (B (Q (n + 1))) ≤ d n)
    (hne : ∀ n k b, Nonempty (NormalPath
      (TubePullbackLimit.pullback B Q n k)
      (shiftData b (TubePullbackLimit.pullback B Q n (k + 1)))))
    {eps : ℕ → ℕ → ℝ} (heps : ∀ n k, 0 < eps n k) :
    Nonempty (PresentedArray B Q K d eps) := by
  choose edgePhase localStep hlocal using
    QuotientPullbackPaths.exists_shift_pullback_step_path
      hK hlip hdefect hne heps
  let phase := accumulatedPhase edgePhase
  let displayed : ℕ → ℕ → Data := fun n k =>
    shiftData (phase n k) (TubePullbackLimit.pullback B Q n k)
  let step : ∀ n k, NormalPath (displayed n k) (displayed n (k + 1)) :=
    fun n k => shiftPathOf (p' := displayed n k) (q' := displayed n (k + 1))
      (phase n k) (localStep n k) (fun _ => rfl) (fun u => by
        change (TubePullbackLimit.pullback B Q n (k + 1)).1
            (u + phase n (k + 1)) =
          (TubePullbackLimit.pullback B Q n (k + 1)).1
            ((u + phase n k) + edgePhase n k)
        rw [show phase n (k + 1) = phase n k + edgePhase n k from rfl]
        congr 1
        ring)
  refine ⟨{
    edgePhase := edgePhase
    phase := phase
    phase_eq := rfl
    displayed := displayed
    displayed_eq := fun _ _ => rfl
    step := step
    step_cost := ?_ }⟩
  intro n k
  simpa [step] using hlocal n k

end QuotientPresentedPullbackPaths
