import Mathlib
import UnitTangentIterates.JointC1
import UnitTangentIterates.RearOwnPathDistIntrinsic
import UnitTangentIterates.SelectedChangeOfVariable

/-!
# Variable-period selected steering and inverse at `C¹`

This module records the first-order compatibility that is lost if the time
derivative of a moving-period curvature is incorrectly declared periodic.
For a jointly `C¹` curvature satisfying

`K(t, s + P(t)) = K(t, s)`, one has

`K_t(t, s + P(t)) + K_s(t, s + P(t)) P'(t) = K_t(t, s)`.

It also gives the corresponding unit-period normalization and packages the
standard joint-`C¹` bridge for a selected steering angle together with the
jointly `C¹` inverse of its rear arclength.  In contrast with the older global
quantitative theorem, no quadratic Taylor remainder is assumed.
-/

noncomputable section

open Function Set Real

namespace SteeringVariablePeriodSelectedInverseJointC1

open RearOwnHigherRegularity RearOwnPathDistIntrinsic RearTrack

variable {K delta deltaT : ℝ → ℝ → ℝ} {P : ℝ → ℝ} {kap : ℝ}

/-- Curvature pulled back from the moving circle of length `P(t)` to the unit
circle. -/
def normalizedCurvature (K : ℝ → ℝ → ℝ) (P : ℝ → ℝ) (t u : ℝ) : ℝ :=
  K t (P t * u)

/-- A field pulled back from the moving circle of length `P(t)` to the unit
circle. -/
def normalizedField (f : ℝ → ℝ → ℝ) (P : ℝ → ℝ) (t u : ℝ) : ℝ :=
  f t (P t * u)

/-- The canonical time derivative of a jointly `C¹` curvature. -/
def curvatureTime (K : ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ := partialTime K

/-- The canonical spatial derivative of a jointly `C¹` curvature. -/
def curvatureSpace (K : ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ := partialArc K

/-- The canonical derivative of the moving period. -/
def periodTime (P : ℝ → ℝ) : ℝ → ℝ := deriv P

/-- Pullback to the unit circle preserves joint `C¹` regularity. -/
theorem normalizedCurvature_contDiff_one
    (hK : ContDiff ℝ 1 (uncurry K)) (hP : ContDiff ℝ 1 P) :
    ContDiff ℝ 1 (uncurry (normalizedCurvature K P)) := by
  have hmap : ContDiff ℝ 1 (fun p : ℝ × ℝ => (p.1, P p.1 * p.2)) :=
    contDiff_fst.prodMk ((hP.comp contDiff_fst).mul contDiff_snd)
  exact hK.comp hmap

/-- The time derivative of the normalized curvature contains the transport
term generated by the moving period. -/
theorem hasDerivAt_normalizedCurvature_time
    (hK : ContDiff ℝ 1 (uncurry K)) (hP : ContDiff ℝ 1 P) (t u : ℝ) :
    HasDerivAt (fun r => normalizedCurvature K P r u)
      (curvatureTime K t (P t * u) +
        curvatureSpace K t (P t * u) * (periodTime P t * u)) t := by
  have hKdiff : Differentiable ℝ (uncurry K) := hK.differentiable (by norm_num)
  have hPdiff : Differentiable ℝ P := hP.differentiable (by norm_num)
  have hu : HasDerivAt (fun r => P r * u) (periodTime P t * u) t := by
    simpa [periodTime] using (hPdiff t).hasDerivAt.mul_const u
  have h := hasDerivAt_moving_point hKdiff hu
  simpa [normalizedCurvature, curvatureTime, curvatureSpace, smul_eq_mul] using
    h.congr_deriv (by simp only [smul_eq_mul]; ring)

/-- The spatial derivative of the normalized curvature is scaled by the
current period. -/
theorem hasDerivAt_normalizedCurvature_space
    (hK : ContDiff ℝ 1 (uncurry K)) (t u : ℝ) :
    HasDerivAt (normalizedCurvature K P t)
      (P t * curvatureSpace K t (P t * u)) u := by
  have hKdiff : Differentiable ℝ (uncurry K) := hK.differentiable (by norm_num)
  have hu : HasDerivAt (fun v : ℝ => P t * v) (P t) u := by
    simpa using (hasDerivAt_id u).const_mul (P t)
  have hs : HasDerivAt (K t) (curvatureSpace K t (P t * u)) (P t * u) := by
    simpa [curvatureSpace] using hasDerivAt_partialArc hKdiff t (P t * u)
  simpa [normalizedCurvature, mul_comm] using hs.comp u hu

/-- A moving-period curvature becomes `1`-periodic after normalization. -/
theorem normalizedCurvature_periodic
    (hKper : ∀ t, Function.Periodic (K t) (P t)) (t : ℝ) :
    Function.Periodic (normalizedCurvature K P t) 1 := by
  intro u
  rw [normalizedCurvature, normalizedCurvature]
  convert hKper t (P t * u) using 1 <;> ring_nf

/-- **Differentiated moving-period compatibility.**  This is the correct
replacement for the generally false assertion that `K_t(t, ·)` is
`P(t)`-periodic. -/
theorem curvatureTime_shift
    (hK : ContDiff ℝ 1 (uncurry K)) (hP : ContDiff ℝ 1 P)
    (hKper : ∀ t, Function.Periodic (K t) (P t)) (t s : ℝ) :
    curvatureTime K t (s + P t) +
        curvatureSpace K t (s + P t) * periodTime P t =
      curvatureTime K t s := by
  have hKdiff : Differentiable ℝ (uncurry K) := hK.differentiable (by norm_num)
  have hPdiff : Differentiable ℝ P := hP.differentiable (by norm_num)
  have hmove : HasDerivAt (fun r => K r (s + P r))
      (curvatureTime K t (s + P t) +
        curvatureSpace K t (s + P t) * periodTime P t) t := by
    have hp : HasDerivAt (fun r => s + P r) (periodTime P t) t := by
      simpa [periodTime] using (hPdiff t).hasDerivAt.const_add s
    have h := hasDerivAt_moving_point hKdiff hp
    simpa [curvatureTime, curvatureSpace, smul_eq_mul] using
      h.congr_deriv (by simp only [smul_eq_mul]; ring)
  have hfixed : HasDerivAt (fun r => K r (s + P r)) (curvatureTime K t s) t := by
    have heq : (fun r => K r (s + P r)) = fun r => K r s := by
      funext r
      exact hKper r s
    rw [heq]
    simpa [curvatureTime] using hasDerivAt_partialTime hKdiff t s
  exact hmove.unique hfixed

/-- The canonical time derivative of the normalized curvature is genuinely
`1`-periodic.  Expanding this statement gives `curvatureTime_shift`. -/
theorem normalizedCurvature_time_periodic
    (hK : ContDiff ℝ 1 (uncurry K)) (hP : ContDiff ℝ 1 P)
    (hKper : ∀ t, Function.Periodic (K t) (P t)) (t : ℝ) :
    Function.Periodic
      (fun u => curvatureTime K t (P t * u) +
        curvatureSpace K t (P t * u) * (periodTime P t * u)) 1 := by
  intro u
  have hC := normalizedCurvature_contDiff_one (K := K) (P := P) hK hP
  have hdiff : Differentiable ℝ (uncurry (normalizedCurvature K P)) :=
    hC.differentiable (by norm_num)
  have hleft := hasDerivAt_normalizedCurvature_time (K := K) (P := P) hK hP t (u + 1)
  have hright := hasDerivAt_normalizedCurvature_time (K := K) (P := P) hK hP t u
  have heq : (fun r => normalizedCurvature K P r (u + 1)) =
      fun r => normalizedCurvature K P r u := by
    funext r
    exact normalizedCurvature_periodic hKper r u
  rw [heq] at hleft
  exact hleft.unique hright

/-- A jointly `C¹` family has a first-order time expansion which is uniform
on the compact unit circle.  This is the qualitative replacement for the
global quadratic Taylor hypothesis used by the older quantitative theorem. -/
theorem uniform_time_remainder_on_unit {f : ℝ → ℝ → ℝ}
    (hf : ContDiff ℝ 1 (uncurry f)) (a : ℝ) :
    ∀ ε > 0, ∃ ρ > 0, ∀ b, |b - a| < ρ → ∀ u ∈ Icc (0 : ℝ) 1,
      |f b u - f a u - (b - a) * partialTime f a u| ≤ ε * |b - a| := by
  intro ε hε
  have hfdiff : Differentiable ℝ (uncurry f) := hf.differentiable (by norm_num)
  have hftc : Continuous (uncurry (partialTime f)) :=
    (contDiff_partialTime_self (n := 0) hf).continuous
  let C : Set (ℝ × ℝ) := Icc (a - 1) (a + 1) ×ˢ Icc (0 : ℝ) 1
  have hC : IsCompact C := isCompact_Icc.prod isCompact_Icc
  have huc : UniformContinuousOn (uncurry (partialTime f)) C :=
    hC.uniformContinuousOn_of_continuous hftc.continuousOn
  obtain ⟨d, hd, hclose⟩ := Metric.uniformContinuousOn_iff.mp huc ε hε
  refine ⟨min 1 d, lt_min one_pos hd, ?_⟩
  intro b hba u hu
  have hba1 : |b - a| < 1 := lt_of_lt_of_le hba (min_le_left _ _)
  have hbad : |b - a| < d := lt_of_lt_of_le hba (min_le_right _ _)
  let g : ℝ → ℝ := fun r => f r u - (r - a) * partialTime f a u
  have hgderiv : ∀ r ∈ uIcc a b, HasDerivWithinAt g
      (partialTime f r u - partialTime f a u) (uIcc a b) r := by
    intro r hr
    have h1 : HasDerivAt (fun q => f q u) (partialTime f r u) r :=
      hasDerivAt_partialTime hfdiff r u
    have h2 : HasDerivAt (fun q : ℝ => (q - a) * partialTime f a u)
        (partialTime f a u) r := by
      simpa using ((hasDerivAt_id r).sub_const a).mul_const (partialTime f a u)
    exact (h1.sub h2).hasDerivWithinAt
  have hgbd : ∀ r ∈ uIcc a b, ‖partialTime f r u - partialTime f a u‖ ≤ ε := by
    intro r hr
    have hra : |r - a| ≤ |b - a| := JointC1.abs_sub_le_of_mem_uIcc hr
    have hrI : r ∈ Icc (a - 1) (a + 1) := by
      rw [abs_le] at hra
      constructor <;> linarith [hba1]
    have hpa : (a, u) ∈ C := by
      exact ⟨⟨by linarith, by linarith⟩, hu⟩
    have hpr : (r, u) ∈ C := ⟨hrI, hu⟩
    have hdist : dist ((r, u) : ℝ × ℝ) (a, u) < d := by
      rw [Prod.dist_eq, Real.dist_eq, Real.dist_eq, sub_self, abs_zero,
        max_eq_left (abs_nonneg (r - a))]
      exact lt_of_le_of_lt hra hbad
    have hc := hclose (r, u) hpr (a, u) hpa hdist
    simpa [Real.dist_eq] using hc.le
  have hmvt := Convex.norm_image_sub_le_of_norm_hasDerivWithin_le hgderiv hgbd
    (convex_uIcc a b) Set.left_mem_uIcc Set.right_mem_uIcc
  have hga : g a = f a u := by simp [g]
  have hgb : g b = f b u - (b - a) * partialTime f a u := rfl
  rw [hga, hgb, Real.norm_eq_abs] at hmvt
  convert hmvt using 1 <;> ring

/-- Uniform convergence of the time difference quotients on the unit circle,
obtained from joint `C¹` regularity alone. -/
theorem uniform_time_difference_quotient_on_unit {f : ℝ → ℝ → ℝ}
    (hf : ContDiff ℝ 1 (uncurry f)) (a : ℝ) :
    ∀ ε > 0, ∃ ρ > 0, ∀ h, h ≠ 0 → |h| < ρ → ∀ u ∈ Icc (0 : ℝ) 1,
      |(f (a + h) u - f a u) / h - partialTime f a u| ≤ ε := by
  intro ε hε
  obtain ⟨ρ, hρ, hr⟩ := uniform_time_remainder_on_unit hf a ε hε
  refine ⟨ρ, hρ, ?_⟩
  intro h hh hsmall u hu
  have hb := hr (a + h) (by simpa using hsmall) u hu
  have habs : 0 < |h| := abs_pos.mpr hh
  have halg : (f (a + h) u - f a u) / h - partialTime f a u =
      (f (a + h) u - f a u - h * partialTime f a u) / h := by
    field_simp
  have heq :
      |(f (a + h) u - f a u) / h - partialTime f a u| =
        |f (a + h) u - f a u - h * partialTime f a u| / |h| := by
    rw [halg, abs_div]
  rw [show a + h - a = h by ring] at hb
  rw [heq]
  exact (div_le_iff₀ habs).2 hb

/-- The time derivative of a fixed-period jointly differentiable family has
the same fixed period. -/
theorem partialTime_periodic_of_periodic {f : ℝ → ℝ → ℝ}
    (hf : ContDiff ℝ 1 (uncurry f)) (hper : ∀ t, Function.Periodic (f t) 1)
    (t : ℝ) : Function.Periodic (partialTime f t) 1 := by
  intro u
  have hfdiff : Differentiable ℝ (uncurry f) := hf.differentiable (by norm_num)
  have h1 : HasDerivAt (fun r => f r (u + 1)) (partialTime f t (u + 1)) t :=
    hasDerivAt_partialTime hfdiff t (u + 1)
  have h2 : HasDerivAt (fun r => f r u) (partialTime f t u) t :=
    hasDerivAt_partialTime hfdiff t u
  have heq : (fun r => f r (u + 1)) = fun r => f r u := by
    funext r
    exact hper r u
  rw [heq] at h1
  exact h1.unique h2

/-- Uniform convergence of the time difference quotients on all of `ℝ` for
a `1`-periodic jointly `C¹` family. -/
theorem uniform_time_difference_quotient {f : ℝ → ℝ → ℝ}
    (hf : ContDiff ℝ 1 (uncurry f)) (hper : ∀ t, Function.Periodic (f t) 1)
    (a : ℝ) :
    ∀ ε > 0, ∃ ρ > 0, ∀ h, h ≠ 0 → |h| < ρ → ∀ u,
      |(f (a + h) u - f a u) / h - partialTime f a u| ≤ ε := by
  intro ε hε
  obtain ⟨ρ, hρ, hr⟩ := uniform_time_difference_quotient_on_unit hf a ε hε
  refine ⟨ρ, hρ, ?_⟩
  intro h hh hsmall u
  let E : ℝ → ℝ := fun x =>
    (f (a + h) x - f a x) / h - partialTime f a x
  have hEper : Function.Periodic E 1 := by
    intro x
    simp only [E, hper (a + h) x, hper a x,
      partialTime_periodic_of_periodic hf hper a x]
  have huRange : E u ∈ Set.range E := ⟨u, rfl⟩
  rw [← hEper.image_Icc one_pos 0] at huRange
  obtain ⟨v, hv, hev⟩ := huRange
  change |E u| ≤ ε
  rw [← hev]
  exact hr h hh hsmall v (by simpa [E] using hv)

/-- The ordinary one-variable difference quotients of a `C¹` period function
converge locally uniformly (there is no spatial variable in this case). -/
theorem uniform_period_difference_quotient (hP : ContDiff ℝ 1 P) (a : ℝ) :
    ∀ ε > 0, ∃ ρ > 0, ∀ h, h ≠ 0 → |h| < ρ →
      |(P (a + h) - P a) / h - periodTime P a| ≤ ε := by
  let Q : ℝ → ℝ → ℝ := fun t _ => P t
  have hQ : ContDiff ℝ 1 (uncurry Q) := hP.comp contDiff_fst
  have hQper : ∀ t, Function.Periodic (Q t) 1 := fun _ _ => rfl
  have hfull := uniform_time_difference_quotient hQ hQper a
  intro ε hε
  obtain ⟨ρ, hρ, hr⟩ := hfull ε hε
  refine ⟨ρ, hρ, ?_⟩
  intro h hh hs
  have hQdiff : Differentiable ℝ (uncurry Q) := hQ.differentiable (by norm_num)
  have hPdiff : Differentiable ℝ P := hP.differentiable (by norm_num)
  have hpt : partialTime Q a 0 = periodTime P a :=
    (hasDerivAt_partialTime hQdiff a 0).unique (by
      simpa [Q, periodTime] using (hPdiff a).hasDerivAt)
  simpa [Q, hpt] using hr h hh hs 0

/-- **Selected steering and inverse, jointly `C¹`.**

Once the (correct, possibly drifting) first variation `deltaT` of a selected
steering is known and jointly continuous, continuous partial derivatives give
joint `C¹` regularity.  The inverse of the rear-arclength family then exists
and is jointly `C¹`.  This qualitative theorem has no Lipschitz constants and
no quadratic Taylor hypotheses. -/
theorem exists_selected_inverse_jointC1
    (hkap0 : 0 ≤ kap) (hkap1 : kap < 1)
    (hK : ContDiff ℝ 1 (uncurry K)) (hP : ContDiff ℝ 1 P)
    (hKper : ∀ t, Function.Periodic (K t) (P t))
    (hdelta : Continuous (uncurry delta))
    (hdeltaT : ∀ t s, HasDerivAt (fun r => delta r s) (deltaT t s) t)
    (hdeltaTc : Continuous (uncurry deltaT))
    (hsteer : ∀ t s, HasDerivAt (delta t) (K t s - Real.sin (delta t s)) s)
    (hstrip : ∀ t s, delta t s ∈ Icc (0 : ℝ) (Real.arcsin kap)) :
    ContDiff ℝ 1 (uncurry delta) ∧
      ∃ sf : ℝ → ℝ → ℝ,
        (∀ t x, rearArclength (delta t) (sf t x) = x) ∧
        ContDiff ℝ 1 (uncurry sf) ∧
        ∀ t s, curvatureTime K t (s + P t) +
            curvatureSpace K t (s + P t) * periodTime P t =
          curvatureTime K t s := by
  have hspacec : Continuous (uncurry fun t s => K t s - Real.sin (delta t s)) := by
    exact hK.continuous.sub (Real.continuous_sin.comp hdelta)
  have hdeltaC1 : ContDiff ℝ 1 (uncurry delta) :=
    JointC1.contDiff_one_of_continuous_partials hdeltaT hsteer hdeltaTc hspacec
  obtain ⟨sf, hsf⟩ := SelectedChangeOfVariable.exists_sf_family hkap0 hkap1 hdelta
    (fun t s => (hstrip t s).1) (fun t s => (hstrip t s).2)
  refine ⟨hdeltaC1, sf, hsf, ?_, ?_⟩
  · exact SelectedChangeOfVariable.contDiff_one_sf hkap0 hkap1 hdelta hdeltaT hdeltaTc
      (fun t s => (hstrip t s).1) (fun t s => (hstrip t s).2) hsf
  · exact curvatureTime_shift hK hP hKper

end SteeringVariablePeriodSelectedInverseJointC1
